// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_finished_wave_1 = "CgkI9OO2ssgEEAIQAw"; // <GPGSID>
        public const string achievement_completed_stage_2 = "CgkI9OO2ssgEEAIQBQ"; // <GPGSID>
        public const string achievement_completed_stage_1 = "CgkI9OO2ssgEEAIQBA"; // <GPGSID>
        public const string achievement_over_9000 = "CgkI9OO2ssgEEAIQDA"; // <GPGSID>
        public const string achievement_dead_man_walking = "CgkI9OO2ssgEEAIQCg"; // <GPGSID>
        public const string achievement_brainssss = "CgkI9OO2ssgEEAIQCQ"; // <GPGSID>
        public const string achievement_completed_stage_3 = "CgkI9OO2ssgEEAIQBg"; // <GPGSID>
        public const string leaderboard_undead_high_scores = "CgkI9OO2ssgEEAIQAQ"; // <GPGSID>
        public const string achievement_payback_given = "CgkI9OO2ssgEEAIQCw"; // <GPGSID>
        public const string leaderboard_riot_high_scores = "CgkI9OO2ssgEEAIQAA"; // <GPGSID>
        public const string achievement_completed_stage_5 = "CgkI9OO2ssgEEAIQCA"; // <GPGSID>
        public const string achievement_completed_stage_4 = "CgkI9OO2ssgEEAIQBw"; // <GPGSID>

}

